### ISSUE TITLE
Use scout config chunk sizes

### ISSUE THREAD

**Issue by FrittenKeeZ** [outl1ne/laravel-scout-batch-searchable#4]
Would it make sense to use Scout's already defined chunk sizes for batching, instead of defining one explicitly?
```php
'chunk' => [
    'searchable'   => 500,
    'unsearchable' => 500,
],
```

**Comment by Tarpsvo** [comment]
Theoretically yeah, but it's still different functionality and I don't think it's really safe to mix and match those. I'd keep them separate for now.
