### ISSUE TITLE
Delete is not added to batch

### ISSUE THREAD

**Issue by GeertHauwaerts** [outl1ne/laravel-scout-batch-searchable#8]
When deleting a record (`$record->delete()`), it is not added to the batch job.

For testing, I switched back to `use Searchable`, deleted the record, and it is removed from the index. When I use `use BatchSearchable`, deleted records are not removed from the index.

I use the latest Laravel/Scout/Horizon.

**Comment by GeertHauwaerts** [comment]
I also added a `boot()` methods with `static::deleted()` and `$model->unsearchable()` (together with a debug log to check if triggered). I can see that the method and unsearchable is called, but it is not pushed into the batch job.

**Comment by GeertHauwaerts** [comment]
The code uses:

```
            $models = method_exists($this, 'trashed')
                ? $className::withTrashed()->findMany($cachedValue['models'])
                : $className::findMany($cachedValue['models']);
```

But `findMany()` will never return anything since the data is already deleted, as the Scout observer listens to `deleted` (https://github.com/laravel/scout/blob/a437210d494214c2fb4e7a5233c318209e12c611/src/ModelObserver.php#L118).

**Comment by GeertHauwaerts** [comment]
I did some testing and the following works, though I am not sure it is the best way to do this. Let me know your thoughts:

```
private function checkBatchingStatusAndDispatchIfNecessaryFor($className, $makeSearchable = true)
{
    ....
            if ($makeSearchable) {
                $models = method_exists($this, 'trashed')
                    ? $className::withTrashed()->findMany($cachedValue['models'])
                    : $className::findMany($cachedValue['models']);
            } else {
                $models = collect();
                $key = (new $className)->getKeyName();

                foreach ($cachedValue['models'] as $id) {
                    $model = new $className();
                    $model->$key = $id;
                    $models->add($model);
                }
            }
    ....
}
```

**Comment by Tarpsvo** [comment]
Okay, version 2.1.1 was an absolute blunder. There is no way the models can be stored and later re-used. The job input sizes were crazy. Version 2.2.0 I just published uses the approach you suggested which is the easiest solution to the problem. :)
